export const PROFORMAS_LIST_MOCK = [
  {
    id: 1,
    usuario: 'KA2341',
    nombreApellido: 'Karem Monica Saucedo Echevarria',
    pais: 'Perú',
    rango: 'Esmeralda',
    fechaRegistro: '2025-04-20',
    tipoSocio: 'Precalificado',
    estado: 'Sin revisar',
  },
  {
    id: 2,
    usuario: 'AF2344',
    nombreApellido: 'Antonella Vanessa Medez Morales',
    pais: 'Perú',
    rango: 'Esmeralda',
    fechaRegistro: '2025-04-20',
    tipoSocio: 'Calificado',
    estado: 'Sin revisar',
  },
  {
    id: 3,
    usuario: 'JP2377',
    nombreApellido: 'Adrián Carlos Flores Benites',
    pais: 'Perú',
    rango: 'Diamante',
    fechaRegistro: '2025-04-20',
    tipoSocio: 'Precalificado',
    estado: 'Sin revisar',
  },
  {
    id: 4,
    usuario: 'JR2366',
    nombreApellido: 'Juan Marcos Perez Sandoval',
    pais: 'Perú',
    rango: 'Diamante',
    fechaRegistro: '2025-04-20',
    tipoSocio: 'Calificado',
    estado: 'Sin revisar',
  },
  {
    id: 5,
    usuario: 'AM2355',
    nombreApellido: 'Ruby Felicitas Rodriguez Nuñuvero',
    pais: 'Perú',
    rango: 'Triple Diamante',
    fechaRegistro: '2025-04-20',
    tipoSocio: 'Calificado',
    estado: 'Sin revisar',
  },
];
