export enum Pages {
    MY_PURCHASES = 'MY_PURCHASES',
    MY_TICKETS = 'MY_TICKETS',
    MY_DETAILS_TICKETS = 'MY_DETAILS_TICKETS',
    MY_PASSWORD = 'My_PASSWORD',
    MY_PROFILE = 'MY_PROFILE',
    MY_MARKET = 'MY_MARKET'
}

