package world.inclub.membershippayment.domain.enums;


public enum  CodigoTypeWalletTransaction {
    RETIRO(1),
    PAGO_CUOTA(2),
    BONO_RECOMENDACION_DIRECTA(3),
    BONIFICACION_RESIDUAL(4),
    BONIFICACION_ARRANQUE_RAPIDO(5),
    BONO_RESERVA(6),
    BONIFICACION_EQUIPO(7),
    BONO_PERIODO(8),
    COMPRA_SERVICIOS_INTERNOS(9),
    PAGO_ADELANTO_CUOTAS(10),
    AMORTIZACION_CRONOGRAMA(11),
    ENVIO_TRANSFERENCIA(12),
    RECEPCION_TRANSFERENCIA(13),
    COMPRA_SUSCRIPCION_EXTRA(14),
    REGISTRO_SOCIO(15),
    UPGRADE_SUSCRIPCION(16),
    PRESTAMO_INCLUB(17),
    DEVOLUCION_PRESTAMO(18),
    DESCUENTO_INCLUB(19),
    DEPOSITO_BASE_DATOS(20),
    BONO_PAGO_CUOTA(21),
    BONO_SEGUNDA_MEMBRESIA(22),
    BONO_MIGRACION(23),
    ENVIO_TRANSFERENCIA_PAGO_DESPUES(24),
    RECEPCION_TRANSFERENCIA_PAGO_DESPUES(25),
    DEVOLUCION_TRANSFERENCIA(26),
    DEVOLUCION_SALDO(27),
    BONIFICACION_MARCAS_EXCLUSIVAS(30),
    RETIRO_MARCAS_EXCLUSIVAS(31);

    private final int code;

    CodigoTypeWalletTransaction(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
