import { ITableLiquidationRequest } from '@interfaces/liquidation.interface';

export const tableDataMock: ITableLiquidationRequest[] = [
	{
		id: 1,
		dateRequest: '13/07/2024',
		username: 'KF01254107',
		nickname: 'KF01254107',
		fullname: 'Karen Angie Flores Cáceres',
		briefcase: 'KeOla',
		membership: [
			{
				id: 1,
				name: 'Infinite Premium',
				description: 'Inicial N° 1',
				dueDate: '20/07/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/07/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			},
			{
				id: 2,
				name: 'Infinite Premium',
				description: 'Cuota N° 1',
				dueDate: '20/08/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/08/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			},
			{
				id: 3,
				name: 'Infinite Premium',
				description: 'Cuota N° 2',
				dueDate: '20/09/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/09/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			}
		],
		reason: 'No desea tener la membresía'
	},
	{
		id: 2,
		dateRequest: '13/07/2024',
		username: 'PS04741761',
		nickname: 'PS04741761',
		fullname: 'Paul Robert Suarez Ann',
		briefcase: 'InResort',
		membership: [
			{
				id: 1,
				name: 'Vitalicia',
				description: 'Inicial N° 1',
				dueDate: '20/07/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/07/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			},
			{
				id: 2,
				name: 'Vitalicia',
				description: 'Cuota N° 1',
				dueDate: '20/08/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/08/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			},
			{
				id: 3,
				name: 'Vitalicia',
				description: 'Cuota N° 2',
				dueDate: '20/09/2024',
				capital: 50,
				amortization: 50,
				interest: 0,
				debt: 0,
				quota: 50,
				total: 50,
				payDate: '20/09/2024',
				familyPackageName: 'INRESORTS RIBERA DEL RÍO',
				idFamilyPackage: 2,
				idPackage: 16,
				idSuscription: 28,
				packageName: "Stand By"
			}
		],
		reason: 'No desea tener la membresía'
	}
];
