export const CAR_ASSIGNMENT_MOCK = [
  {
    id: 1,
    nombreSocio: 'Karem Saucedo',
    modeloCarro: 'Civic/Honda',
    precioAuto: 15000,
    cuota: 60,
    cuotasPagadas: 5,
    bonoAsignado: 250,
    cuotasMensuales: null,
    rangoActual: 'Esmeralda',
    fechaAsignacion: '2025-04-04',
  },
  {
    id: 2,
    nombreSocio: 'Adrián Flores',
    modeloCarro: 'Corolla/Toyota',
    precioAuto: 20000,
    cuota: 80,
    cuotasPagadas: 10,
    bonoAsignado: 250,
    cuotasMensuales: 2500,
    rangoActual: 'Esmeralda',
    fechaAsignacion: '2024-06-10',
  },
  {
    id: 3,
    nombreSocio: 'Juan Perez',
    modeloCarro: 'Corolla/Toyota',
    precioAuto: 20000,
    cuota: 80,
    cuotasPagadas: 9,
    bonoAsignado: 250,
    cuotasMensuales: 2250,
    rangoActual: 'Esmeralda',
    fechaAsignacion: '2024-07-15',
  },
  {
    id: 4,
    nombreSocio: 'Ruby Rodríguez',
    modeloCarro: 'Corolla/Toyota',
    precioAuto: 20000,
    cuota: 80,
    cuotasPagadas: 3,
    bonoAsignado: 250,
    cuotasMensuales: 750,
    rangoActual: 'Diamante',
    fechaAsignacion: '2025-01-03',
  },
  {
    id: 5,
    nombreSocio: 'Antonella Mendez',
    modeloCarro: 'Civic/Honda',
    precioAuto: 15000,
    cuota: 60,
    cuotasPagadas: 20,
    bonoAsignado: 250,
    cuotasMensuales: 5000,
    rangoActual: 'Esmeralda',
    fechaAsignacion: '2023-08-23',
  },
];
