export const DOCUMENTS_MOCK = [
  {
    id: 1,
    usuario: 'KA2341',
    nombresApellidos: 'Karem Monica Saucedo Echevarria',
    auto: 'CHERY TIGGO 2 PRO - Rojo',
    rango: 'Esmeralda',
    ultimaModificacion: '2025-04-20',
    numeroDocumentos: 4,
  },
  {
    id: 2,
    usuario: 'AF2344',
    nombresApellidos: 'Antonella Vanessa Medez Morales',
    auto: 'HYUNDAI VENUE 2025 - Azul',
    rango: 'Esmeralda',
    ultimaModificacion: '2025-04-20',
    numeroDocumentos: 4,
  },
  {
    id: 3,
    usuario: 'JP2377',
    nombresApellidos: 'Adrián Carlos Flores Benites',
    auto: 'MAZDA CX-5 Touring - Rojo',
    rango: 'Diamante',
    ultimaModificacion: '2025-04-20',
    numeroDocumentos: 4,
  },
  {
    id: 4,
    usuario: 'JR2366',
    nombresApellidos: 'Juan Marcos Perez Sandoval',
    auto: 'TOYOTA COROLLA 2024 - Gris',
    rango: 'Diamante',
    ultimaModificacion: '2025-04-20',
    numeroDocumentos: 4,
  },
  {
    id: 5,
    usuario: 'AM2355',
    nombresApellidos: 'Ruby Felicitas Rodriguez Nuñuvero',
    auto: 'KIA SPORTAGE LX - Blanco',
    rango: 'Triple Diamante',
    ultimaModificacion: '2025-04-20',
    numeroDocumentos: 4,
  },
];
