spring:
  application.name: bo-legal-microservice
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URI:https://oauth-dev.inclub.world}

database:
  host: ${DB_HOSTNAME}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  driver: postgresql

server:
  port: ${SERVER_PORT:8776}

external-services:
  admin-panel-base-url: https://adminpanelapi-dev.inclub.world/api/
  account-base-url: https://account-dev.inclub.world/api/v1/
  notification-base-url: https://notifications-dev.inclub.world/
  document-base-url: https://documentapi-dev.inclub.world/api/v1/s3
  pdf-base-url: https://pdfapi-dev.inclub.world/

springdoc:
  swagger-ui:
    use-root-path: true
    oauth:
      clientId: back-office
      clientSecret: secret

logging:
  level:
    root: ${LOG_LVL_ROOT:INFO}
    org.apache.kafka: ${LOG_LVL_KAFKA:ERROR}
    kafka: ${LOG_LVL_KAFKA:ERROR}
    org.springframework.kafka: ${LOG_LVL_KAFKA:ERROR}
    world.inclub.account: ${LOG_LVL_APP:INFO}

application:
  name: bo-account-microservice
  description: bo-legal-microservice
  version: v0.0.1-SNAPSHOT
  inceptionYear: 2025
