spring:
  application:
    name: bo-migrations-microservice
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://${DB_HOSTNAME:212.56.44.91}:${DB_PORT:31334}/${DB_NAME:dev_bo_migrations}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:CsOyVa08Q835}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URI:https://oauth-dev.inclub.world}

  kafka:
    bootstrap-servers: ${KAFKA_HOSTNAME:kafka.inclub.world}:${KAFKA_PORT:29093}
  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}

server:
  port: ${SERVER_PORT:9098}