export const BONUS_PAYMENTS_MOCK = [
  {
    id: 1,
    userSocio: 'TS6123457',
    usuario: 'Tafat Salinas Yucra',
    fechaDescuento: '2025-10-05',
    montoRecargaUSD: 0,
    montoDescuentoUSD: 330.23,
    conceptoDescuento: 'Toyota / Hilux 4x4 - Cuota N°: 01',
    medioPago: 'Wallet',
    estado: 'Por Pagar',
  },
  {
    id: 2,
    userSocio: 'FM6123457',
    usuario: 'Fabrizio Molina Quispe',
    fechaDescuento: '2025-10-05',
    montoRecargaUSD: 450,
    montoDescuentoUSD: 905.21,
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 04',
    medioPago: 'Wallet',
    estado: 'Por Pagar',
  },
  {
    id: 3,
    userSocio: 'FM6123457',
    usuario: 'Andrea Quispe Mamani',
    fechaDescuento: '2025-10-05',
    montoRecargaUSD: 250,
    montoDescuentoUSD: 650.65,
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 05',
    medioPago: 'Wallet',
    estado: 'Por Pagar',
  },
  {
    id: 4,
    userSocio: 'FM6123457',
    usuario: 'Pedro Mengoa Valverde',
    fechaDescuento: '2025-10-05',
    montoRecargaUSD: 450,
    montoDescuentoUSD: 541.31,
    conceptoDescuento: 'Toyota / Corolla - Inicial N°: 04',
    medioPago: 'Wallet',
    estado: 'Por Pagar',
  },
  {
    id: 5,
    userSocio: 'JQ6123457',
    usuario: 'James Quiroz',
    fechaDescuento: '2025-10-05',
    montoRecargaUSD: 580,
    montoDescuentoUSD: 128.85,
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 06',
    medioPago: 'Wallet',
    estado: 'Por Pagar',
  },
];
