export const PROFORMAS_SELECTED_MOCK = [
  {
    id: 1,
    usuario: 'KA2341',
    nombresApellidos: 'Karem Monica Saucedo Echevarria',
    pais: 'Perú',
    rango: 'Esmeralda',
    fechaRegistro: '2025-04-20',
    proforma: true,
  },
  {
    id: 2,
    usuario: 'AF2344',
    nombresApellidos: 'Antonella Vanessa Medez Morales',
    pais: 'Perú',
    rango: 'Esmeralda',
    fechaRegistro: '2025-04-20',
    proforma: true,
  },
  {
    id: 3,
    usuario: 'JP2377',
    nombresApellidos: 'Adrián Carlos Flores Benites',
    pais: 'Perú',
    rango: 'Diamante',
    fechaRegistro: '2025-04-20',
    proforma: true,
  },
  {
    id: 4,
    usuario: 'JR2366',
    nombresApellidos: 'Juan Marcos Perez Sandoval',
    pais: 'Perú',
    rango: 'Diamante',
    fechaRegistro: '2025-04-20',
    proforma: true,
  },
  {
    id: 5,
    usuario: 'AM2355',
    nombresApellidos: 'Ruby Felicitas Rodriguez Nuñuvero',
    pais: 'Perú',
    rango: 'Triple Diamante',
    fechaRegistro: '2025-04-20',
    proforma: true,
  },
];
