import { Environment } from '@shared/interfaces/environment';

export const environment: Environment = {
	URL_API: 'https://usersapi.inclub.world',
	URL_API_CALENDAR: 'https://scheduleapi.inclub.world/api/v1',
	LOGIN_USER_CLIENT: 'client',
	LOGIN_USER_SECRET: 'secret',
	CODE_CHALLENGE: 'meWMSrkRBnMbd5RRseIVwuFGFOU6xwHi0_LgQyCOd1A',
	CODE_CHALLENGE_METHOD: 'S256',
	TOKEN_PAYPAL: 'AYfPhcYfqHQrWxh_819JLMSgNevBqrZM26HM_YmQ8WsJZsV7D25zjtWjUsRqq5ex0bdKd3DGi5xw7xDn',
	CLIENT_ID: 'floofle-client',
	CLIENT_SECRET: 'secret',
	URL_AUTH_SERVER: 'oauth.inclub.world',
	LOGIN_URL: '/oauth2/authorization/backoffice-gateway',
	SHOW_IMAGES_COMPONENT: false,
	URL_IMG: 'https://s3.us-east-2.amazonaws.com/backoffice.documents/bo-imagenes/',
	LOCAL_LOGIN: false,
	URL_ADMIN: 'https://adminpanelapi.inclub.world/api',
	// URL_ADMIN_LOCAL: 'http://localhost:8081/api',
	URL_API_PAYMENT: 'https://membershipapi.inclub.world/api/v1',
	/* 	URL_API_GRACE_PERIOD: 'https://financeapi-dev.inclub.world',
	 */ URL_API_VALIDA_SPONSOR: 'https://adminpanelapi.inclub.world/user/exists',
	URL_API_TRANSFER_LIQUIDATION: 'https://transferapi.inclub.world/api/v1',
	URL_API_REGISTER_MIGRATION: 'https://migrationapi.inclub.world/api/v1',
	URL_API_COMMISSION: 'https://commissionsapi.inclub.world/api/v1',
	URL_API_PDF: 'https://pdfapi.inclub.world/api/v1',
	URL_ACCOUNT: 'https://account.inclub.world/api/v1',
	URL_JOBSTATUSAPI: 'https://jobstatusapi.inclub.world/api/v1',
	URL_GATEWEY: 'https://opengateway.inclub.world/api/v1',
	URL_WALLET: 'https://walletapi.inclub.world/api/v1',
	URL_API_LEGAL: 'https://legalapi.inclub.world/api/v1',
	URL_BONUS_API: 'https://bonusesrewardsapi.inclub.world/api/v1',
	URL_GATEWAY_LOCAL: '',
	URL_API_REWARDS: 'https://rewardsapi.inclub.world/api/v1',
	URL_API_TicketApi: 'https://ticketapi.inclub.world',
	URL_API_TRANSFER: 'https://transferapi.inclub.world/api/v1',
};
