server:
  port: 8888
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
          default-label: main
        azure:
          keyvault:
            uri: ${AZURE_KEYVAULT_URI}
            client-id: ${AZURE_KEYVAULT_CLIENT_ID}
            client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
            tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
        native:
          search-locations: file://${PROPERTIES_DIRECTORY:/Keola InClub/cfg-bo-dev}
  profiles:
    active: ${SERVER_CONFIG_PROFILES:native, keyvault}
