export enum PaymentType {
	CASH = 'cash',
	WALLET = 'WALLET',
	PAYPAL = 'PAYPAL',
	OTROS = 'OTROS',
	DAVIVIENDA = 'DAVIVIENDA',
	INTERBANK = 'INTERBANK',
	BCP = 'BCP',
	// BANCOLOMBIA = 'BANCOLOMBIA'
}
