export const PREQUALIFIED_MOCK = [
  {
    id: 1,
    usuario: 'KA2341',
    nombresApellidos: 'Karem Monica Saucedo Echevarria',
    paisResidencia: 'Perú',
    rango: 'Esmeralda',
    puntosAlcanzados: 13250,
    puntosMeta: 13500,
    puntosFaltantes: 250,
    fechaCierre: '2025-04-20',
    ciclosRecalificados: 5,
    estado: 'Sin notificar',
  },
  {
    id: 2,
    usuario: 'AF2344',
    nombresApellidos: 'Antonella Vanessa Medez Morales',
    paisResidencia: 'Perú',
    rango: 'Esmeralda',
    puntosAlcanzados: 13150,
    puntosMeta: 13500,
    puntosFaltantes: 350,
    fechaCierre: '2025-04-20',
    ciclosRecalificados: 4,
    estado: 'Sin notificar',
  },
  {
    id: 3,
    usuario: 'JP2377',
    nombresApellidos: 'Adrián Carlos Flores Benites',
    paisResidencia: 'Perú',
    rango: 'Diamante',
    puntosAlcanzados: 67190,
    puntosMeta: 67500,
    puntosFaltantes: 310,
    fechaCierre: '2025-04-20',
    ciclosRecalificados: 3,
    estado: 'Sin notificar',
  },
  {
    id: 4,
    usuario: 'JR2366',
    nombresApellidos: 'Juan Marcos Perez Sandoval',
    paisResidencia: 'Perú',
    rango: 'Diamante',
    puntosAlcanzados: 67100,
    puntosMeta: 67500,
    puntosFaltantes: 400,
    fechaCierre: '2025-04-20',
    ciclosRecalificados: 4,
    estado: 'Sin notificar',
  },
  {
    id: 5,
    usuario: 'AM2355',
    nombresApellidos: 'Ruby Felicitas Rodriguez Nuñuvero',
    paisResidencia: 'Perú',
    rango: 'Triple Diamante',
    puntosAlcanzados: 337280,
    puntosMeta: 337500,
    puntosFaltantes: 220,
    fechaCierre: '2025-04-20',
    ciclosRecalificados: 2,
    estado: 'Sin notificar',
  },
];
