export const INSTALLMENTS_PAYMENTS_MOCK = [
  {
    id: 1,
    userSocio: 'TS6123457',
    solicitante: 'Tafat Salinas Yucra',
    fechaDescuento: '2025-04-20',
    montoRecargaUSD: 250,
    montoDescuentoUSD: 330.23,
    bonoAsignado: 'Auto',
    conceptoDescuento: 'Toyota / Hilux 4x4 - Cuota N°: 01',
    medioPago: 'Wallet',
    estado: 'Pagado',
  },
  {
    id: 2,
    userSocio: 'FM6123457',
    solicitante: 'Fabrizio Molina Quispe',
    fechaDescuento: '2025-04-20',
    montoRecargaUSD: 450,
    montoDescuentoUSD: 584.10,
    bonoAsignado: 'Auto',
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 04',
    medioPago: 'Wallet',
    estado: 'Pagado',
  },
  {
    id: 3,
    userSocio: 'FM6123457',
    solicitante: 'Fabrizio Molina Quispe',
    fechaDescuento: '2025-04-20',
    montoRecargaUSD: 450,
    montoDescuentoUSD: 584.10,
    bonoAsignado: 'Auto',
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 05',
    medioPago: 'Wallet',
    estado: 'Pagado',
  },
  {
    id: 4,
    userSocio: 'FM6123457',
    solicitante: 'Fabrizio Molina Quispe',
    fechaDescuento: '2025-04-20',
    montoRecargaUSD: 450,
    montoDescuentoUSD: 584.10,
    bonoAsignado: 'Auto',
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 06',
    medioPago: 'Wallet',
    estado: 'Pagado',
  },
  {
    id: 5,
    userSocio: 'JQ6123457',
    solicitante: 'James Quiroz',
    fechaDescuento: '2025-04-20',
    montoRecargaUSD: 580,
    montoDescuentoUSD: 650.56,
    bonoAsignado: 'Auto',
    conceptoDescuento: 'Toyota / Corolla - Cuota N°: 07',
    medioPago: 'Wallet',
    estado: 'Pagado',
  },
];
