export const QUALIFIED_MOCK = [
  {
    id: 1,
    usuario: 'KA2341',
    nombresApellidos: 'Karem Monica Saucedo Echevarria',
    paisResidencia: 'Perú',
    rango: 'Esmeralda',
    puntosAlcanzados: 13580,
    puntosMeta: 13500,
    ciclosRecalificados: 5,
    fechaCierre: '2025-04-20',
    estado: 'Sin notificar',
  },
  {
    id: 2,
    usuario: 'AF2344',
    nombresApellidos: 'Antonella Vanessa Medez Morales',
    paisResidencia: 'Perú',
    rango: 'Esmeralda',
    puntosAlcanzados: 13600,
    puntosMeta: 13500,
    ciclosRecalificados: 4,
    fechaCierre: '2025-04-20',
    estado: 'Sin notificar',
  },
  {
    id: 3,
    usuario: 'JP2377',
    nombresApellidos: 'Adrián Carlos Flores Benites',
    paisResidencia: 'Perú',
    rango: 'Diamante',
    puntosAlcanzados: 67528,
    puntosMeta: 67500,
    ciclosRecalificados: 3,
    fechaCierre: '2025-04-20',
    estado: 'Sin notificar',
  },
  {
    id: 4,
    usuario: 'JR2366',
    nombresApellidos: 'Juan Marcos Perez Sandoval',
    paisResidencia: 'Perú',
    rango: 'Diamante',
    puntosAlcanzados: 67650,
    puntosMeta: 67500,
    ciclosRecalificados: 4,
    fechaCierre: '2025-04-20',
    estado: 'Sin notificar',
  },
  {
    id: 5,
    usuario: 'AM2355',
    nombresApellidos: 'Ruby Felicitas Rodriguez Nuñuvero',
    paisResidencia: 'Perú',
    rango: 'Triple Diamante',
    puntosAlcanzados: 337550,
    puntosMeta: 337500,
    ciclosRecalificados: 2,
    fechaCierre: '2025-04-20',
    estado: 'Sin notificar',
  },
];
